name: Daily Build
on:
  schedule:
    - cron:  '30 13 * * *'

jobs:
  Build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  NotifySuccess:
    name: Notify
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Restore build
        uses: actions/download-artifact@v4
        with:
          name: ExtBuild
          path: ./

      - name: Set up workspace
        run: |
          unzip build.zip
          rm build.zip
