name: Release VSIX

on:
  workflow_dispatch:
    inputs:
      isPreRelease:
        required: true
        type: boolean
      wso2-platform:
        description: Release WSO2 Platform extension
        type: boolean
        required: true
        default: false
      choreo:
        description: Release Choreo extension
        type: boolean
        required: true
        default: false
      apk:
        description: Release APK extension
        type: boolean
        required: true
        default: false
      hurl-client:
        description: Release Hurl Client extension
        type: boolean
        required: true
        default: false
      version:
        type: choice
        description: 'Enter the version type'
        required: true
        default: 'N/A'
        options:
          - 'patch'
          - 'minor'
          - 'major'    
          - 'N/A'     

jobs:
  Build:
    name: Build branch - ${{ github.ref_name }}
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      runOnAWS: true
      isPreRelease: ${{ inputs.isPreRelease }}
      enableCache: false
      wso2-platform: ${{ inputs.wso2-platform }}
      choreo: ${{ inputs.choreo }}
      apk: ${{ inputs.apk }}
      hurl-client: ${{ inputs.hurl-client }}
      version: ${{ inputs.version }}
      isReleaseBuild: true

  Release:
    name: Release VSIX
    needs: Build
    timeout-minutes: 45
    runs-on: codebuild-wso2_vscode-extensions-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Restore build
        uses: actions/download-artifact@v4
        with:
          name: ExtBuild
          path: ./

      - name: Set up workspace
        run: |
          unzip build.zip
          rm build.zip

      - name: Setup Rush
        uses: gigara/setup-rush@v1.2.0
        with:
          pnpm: 10.10.0
          node: 22.x
          cache-rush: false
          cache-pnpm: false
          set-env: false
          rush-install: true

      - name: Get version
        id: vsix
        run: |
          if [[ "${{ github.event.inputs.wso2-platform }}" == "true" ]]; then
            file=$(ls wso2-platform*.vsix)
          fi  
          if [[ "${{ github.event.inputs.choreo }}" == "true" ]]; then
            file=$(ls choreo*.vsix)
          fi
          if [[ "${{ github.event.inputs.hurl-client }}" == "true" ]]; then
            file=$(ls hurl-client-[0-9]*.[0-9]*.[0-9]*.vsix)
          fi
          version=$(basename "$file" .vsix)
          echo $version
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create a release in wso2/vscode-extensions repo
        if: ${{ github.event.inputs.wso2-platform == 'true' }}
        uses: ./.github/actions/release
        with:
          repo: wso2/vscode-extensions
          name: wso2-platform
          token: ${{ secrets.CHOREO_BOT_TOKEN }}
      
      - name: Create a release in wso2/choreo-vscode repo
        if: ${{ github.event.inputs.choreo == 'true' }}
        uses: ./.github/actions/release
        with:
          repo: wso2/choreo-vscode
          name: choreo
          token: ${{ secrets.CHOREO_BOT_TOKEN }}

      - name: Create a release in wso2/apk repo
        if: ${{ github.event.inputs.apk == 'true' }}
        uses: ./.github/actions/release
        with:
          repo: wso2/apk
          name: apk
          token: ${{ secrets.CHOREO_BOT_TOKEN }}

      - name: Create a release in wso2/ballerina-vscode repo for hurl-client
        if: ${{ github.event.inputs.hurl-client == 'true' }}
        uses: ./.github/actions/release
        with:
          repo: wso2/ballerina-vscode
          token: ${{ secrets.CHOREO_BOT_TOKEN }}
          name: hurl-client

      - name: Create PR
        uses: ./.github/actions/pr
        with:
          version: ${{ steps.vsix.outputs.version }}
          isPreRelease: ${{ github.event.inputs.isPreRelease }}
          bot_username: ${{ secrets.CHOREO_BOT_USERNAME }}
          bot_email: ${{ secrets.CHOREO_BOT_EMAIL }}
          bot_token: ${{ secrets.CHOREO_BOT_TOKEN }}
          ref_name: ${{ github.ref_name }}
          wso2-platform: ${{ inputs.wso2-platform }}
          choreo: ${{ inputs.choreo }}
          apk: ${{ inputs.apk }}
          hurl-client: ${{ inputs.hurl-client }}
